pipeline {
    agent any

    stages {
        stage('Unit tests -Backend') {
            steps {
                dir('bugtracker-backend'){
                    go test -v ./...
                }

                echo 'Hello World'
                sh 'echo "Hello Jenkins"'
                sh 'date'
            }
        }
    }
}
