pipeline {
    agent any

    stages {
        stage('Unit tests -Backend') {
            agent{
                docker {
                    image 'snakee/golang-junit:1.21'
                    args '-u root'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend'){
                    sh 'go test -v ./...'
                }

                
            }
        }
    }
}