pipeline {
    agent any

    stages {
        stage('Unit tests -Backend') {
            agent{
                docker {
                    image 'snakee/golang-junit:1.21'
                    args '-u root'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend'){
                    sh 'go test -v ./...'
                }

                
            }
        }
        
        stage('Unit Tests - Frontend'){
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps{
                dir('bugtracker-frontend'){
                    sh'''
                        npm ci
                        npm test
                    '''
                }
            }
            post{
                always{
                    junit 'backtracker-frontend/test-results.xml'
                }
            }
        }
    }
}