name: my workflow

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

    workflow_dispatch:

jobs:
    bugtracker-backend-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: setup go
              uses: actions/setup-go@v4
              with:
                go-version: '1.21'
                cache-dependency-path: 'bugtracker-backend/go.sum' 
            
            
            - name: Execute unit test
              working-directory: ./bugtracker-backend
              run: |
                go test -v ./...

    bugtracker-frontend-test:
        needs: bugtracker-backend-tests
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: "20"
                cache: "npm"
                cache-dependency-path: bugtracker-frontend/package-lock.json

            - name: Execute frontend Unit tests
              working-directory: ./bugtracker-frontend
              run: |
                npm ci
                npm test
